name: Publish Plugin Specs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  detect-version-bumps:
    name: Detect version bumps
    runs-on: ubuntu-latest
    outputs:
      core_plugin_v1: ${{ steps.check-v1.outputs.bump }}
      core_plugin_v2: ${{ steps.check-v2.outputs.bump }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version bump for core-plugin-v1
        id: check-v1
        run: |
          if git diff "${{ github.event.before }}" "${{ github.event.after }}" -- core-plugin-v1/package.json | grep -E '^\+.*"version":'; then
            echo "::set-output name=bump::true"
          else
            echo "::set-output name=bump::false"
          fi

      - name: Check version bump for core-plugin-v2
        id: check-v2
        run: |
          if git diff "${{ github.event.before }}" "${{ github.event.after }}" -- core-plugin-v2/package.json | grep -E '^\+.*"version":'; then
            echo "::set-output name=bump::true"
          else
            echo "::set-output name=bump::false"
          fi

  publish-v1:
    name: Publish core-plugin-v1
    needs: detect-version-bumps
    if: needs.detect-version-bumps.outputs.core_plugin_v1 == 'true'
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        working-directory: core-plugin-v1

      - name: Publish to npm
        run: bun deploy
        working-directory: core-plugin-v1

  publish-v2:
    name: Publish core-plugin-v2
    needs: detect-version-bumps
    if: needs.detect-version-bumps.outputs.core_plugin_v2 == 'true'
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        working-directory: core-plugin-v2

      - name: Publish to npm
        run: bun deploy
        working-directory: core-plugin-v2